version: "3.7"
services:
  mongodb:
    image: "mongo"
    container_name: "mongodb"
    ports: 
      - "27017:27017"
  web-api:
    build:
      context: ./api
    ports:
      - "20001:20001"
    links: 
      - "mongodb"
    depends_on: 
      - "mongodb"
  web-client:
    build:
      context: ./client
    ports: 
      - "20002:20002"
    depends_on: 
      - "web-api"